## Data Handling Basics Part 1: NumPy (Numerical Computing in Python)

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]

In [3]:
# Python Lists
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]

In [4]:
# Numpy Arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]

NumPy performs element-wise operations.

In [5]:
# Basic Array Operations 

arr = np.array([1,2,3,4])

print(arr+10)
print(arr*2)

[11 12 13 14]
[2 4 6 8]

In [6]:
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

2.5
10
4
1

In [7]:
print('Zeros:',np.zeros(5))
print('Ones:',np.ones(4))
print('Range:', np.arange(1,10))

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1.]
Range: [1 2 3 4 5 6 7 8 9]

In [8]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

In [9]:
# Create NumPy array of numbers 1-10
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]

In [10]:
# Add 5 to every element
print(arr + 5)

[ 6  7  8  9 10 11 12 13 14 15]

In [11]:
# Find mean and sum of array
print(f"Mean: {np.mean(arr)}")
print(f"Sum: {np.sum(arr)}")

Mean: 5.5
Sum: 55

In [12]:
# One dimensional array
myarray = np.array([3,4,5])

print(myarray.shape)

(3,)

In [13]:
# Create a 3 by 3 matrix
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]
])

print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

In [14]:
print(f"Max: {np.max(arr)}")
print(f"Max array3: {np.max(arr3)}")

Max: 10
Max array3: 9

## Data Handling Part 2: Pandas

In [15]:
import pandas as pd

**What is a Series**  

A Series is a one-dimensional labeled array.

In [16]:
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

**What is a DataFrame**  

A DataFrame is a table (like Excel).

In [17]:
data = {
    'Name': ['Amit', 'Deepak', 'Ravi'],
    'Marks': [78,85,90]
}

df = pd.DataFrame(data)
print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
2    Ravi     90

In [18]:
# Reading CSV Files

df = pd.read_csv('students.csv')
print(df)

     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92

In [19]:
# Basic Data Exploration
print(df.head()) 
print(df.tail())
print(df.shape)
print(df.columns)

     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92
     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92
(5, 2)
Index(['Name', 'Marks'], dtype='object')

In [20]:
# Basic Statistics
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())

75.6
92
35

In [21]:
# Sales Data
data = {
    'Product': ['A','B','C'],
    'Sales':[100,150,200]
}

df = pd.DataFrame(data)
print("Total Sales:", df['Sales'].sum())

Total Sales: 450

In [22]:
# Create DataFrame of students with name and marks
data = {
    'Name': ['Amit', 'Deepak', 'Ravi', 'Neha'],
    'Marks': [78,85,90,82]
}
df = pd.DataFrame(data)
print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
2    Ravi     90
3    Neha     82

In [23]:
# Print first 3 row using head()
print(df.head(3))

     Name  Marks
0    Amit     78
1  Deepak     85
2    Ravi     90

In [24]:
# Find average marks
print('Average Marks:', df['Marks'].mean())

Average Marks: 83.75

In [25]:
# Find highest marks
print('Highest Marks:', df['Marks'].max())

Highest Marks: 90

In [26]:
# Select only Name column
df['Name']

0      Amit
1    Deepak
2      Ravi
3      Neha
Name: Name, dtype: object

## Data Handling Basics Part 3: Data Cleaning with Pandas  

Common problems:  
- Missing values
- Duplicate rows
- Wrong data types
- Extra spaces / inconsistent values

In [27]:
# Import pandas 
import pandas as pd

In [28]:
# Detect Missing Values
data = {
    "Name": ['Amit', 'Deepak', 'Ravi', 'Neha'],
    "Marks": [78, None, 90, 82]
}

df = pd.DataFrame(data)
print(df)

     Name  Marks
0    Amit   78.0
1  Deepak    NaN
2    Ravi   90.0
3    Neha   82.0

NaN means missing value.

**Check Missing Values**

In [29]:
# Check Missing Values
print(df.isnull())

print(f"Count missing values: {df.isnull().sum()}")

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False  False
Count missing values: Name     0
Marks    1
dtype: int64

**Remove Missing Values**

In [30]:
# Remove Missing Values
df = df.dropna()
print(df)

   Name  Marks
0  Amit   78.0
2  Ravi   90.0
3  Neha   82.0

This removes rows with missing data.

In [31]:
df

   Name  Marks
0  Amit   78.0
2  Ravi   90.0
3  Neha   82.0

**Fill Missing Values**  

Instead of removing rows:

In [32]:
df

   Name  Marks
0  Amit   78.0
2  Ravi   90.0
3  Neha   82.0

In [33]:
data = pd.DataFrame({
    'Name': ['Amit', 'Deepak', 'Ravi', 'Neha'],
    'Marks': [78, 85, 85, 90]
})

In [34]:
# fill Missing values with 0
df['Marks'] = df['Marks'].fillna(0)

In [35]:
# Or fill with mean
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [36]:
df

   Name  Marks
0  Amit   78.0
2  Ravi   90.0
3  Neha   82.0

**Remove Duplicate Rows**

In [37]:
df = pd.DataFrame({
    "Name": ['Amit', 'Deepak', 'Deepak', 'Ravi'],
    "Marks": [78, 85, 85, 90]
})

print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
2  Deepak     85
3    Ravi     90

In [38]:
# Remove duplicates: 
# df.drop_duplicates() drops a row if every value in that row matches every value in another row
df = df.drop_duplicates()
print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
3    Ravi     90

**Rename Columns**

In [39]:
df.rename(columns={"Marks":"Score"}, inplace=True)
print(df)

     Name  Score
0    Amit     78
1  Deepak     85
3    Ravi     90

**Change Data Types**

In [41]:
df["Score"] = df["Score"].astype(float)

df

     Name  Score
0    Amit   78.0
1  Deepak   85.0
3    Ravi   90.0

**Real Example - Clean Student Dataset**

In [42]:
df = pd.read_csv('students.csv')
df = df.drop_duplicates()
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print(df.head())

     Name  Marks
0    Amit     78
1   Kiran     88
2  Deepak     85
3    Ravi     35
4    Neha     92

## Practice Tasks  

**1. Create DataFrame with missing values**

In [43]:
data = {
    "Name": ['Amit', 'Deepak', 'Ravi', 'Neha'],
    "Marks": [78, None, 90, None]
}

df = pd.DataFrame(data)

print(df)

     Name  Marks
0    Amit   78.0
1  Deepak    NaN
2    Ravi   90.0
3    Neha    NaN

**isna()** and **isnull()** are aliases — they do the same thing and return the same result (**a DataFrame of True/False**)

**2. Detect missing values**

In [44]:
print(df.isnull())
print('\nMissing values count:')
print(df.isnull().sum())

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False   True

Missing values count:
Name     0
Marks    2
dtype: int64

**3. Fill missing values with 0**

In [45]:
df["Marks"] = df["Marks"].fillna(0)
print(df)

     Name  Marks
0    Amit   78.0
1  Deepak    0.0
2    Ravi   90.0
3    Neha    0.0

**4. Remove duplicate rows**

In [46]:
df = pd.DataFrame({
    "Name": ['Amit', 'Deepak', 'Deepak', 'Ravi'],
    "Marks": [78, 85, 85, 90]
})
df = df.drop_duplicates()
print(df)

     Name  Marks
0    Amit     78
1  Deepak     85
3    Ravi     90

**5. Rename column Marks -> Score**

In [47]:
df.rename(columns={'Marks':'Score'}, inplace=True)

print(df)

     Name  Score
0    Amit     78
1  Deepak     85
3    Ravi     90

**Quick Learning**  

- isnull() -> detect missng values
- dropna() -> remove missing rows
- fillna() -> replace missing values
- drop_duplicates() -> remove duplicates

## Sales Data Analysis Project  

Analyze sales data to answers:
- Total sales
- Best-selling product
- Average sales
- Filter high-performing products

**1. Sampled Dataset (sales.csv)**  

**2. Load Data**

In [48]:
df = pd.read_csv('sales.csv')

print(df.head())

  Product  Sales
0       A    100
1       B    150
2       C    200
3       A    120
4       B    180

**3. Basic Analysis**

In [ ]:
# Total Sales
print("Total Sales:", df['Sales'].sum())

# Average Sales
print("Average Sales:", df['Sales'].mean())

# Maximum Sale
print("Max Sale:", df['Sales'].max())

Total Sales: 970
Average Sales: 161.66666666666666
Max Sale: 220

**4. Group by**

In [50]:
# Group by product
grouped = df.groupby("Product")['Sales'].sum()
print(grouped)

Product
A    220
B    330
C    420
Name: Sales, dtype: int64

**5. Find Best-Selling Product**

In [51]:
print("Best Product:", grouped.idxmax())

Best Product: C

**6. Filter High Sales**

In [52]:
high_sales = df[df['Sales'] > 150]
print(high_sales)

  Product  Sales
2       C    200
4       B    180
5       C    220

In [53]:
df

  Product  Sales
0       A    100
1       B    150
2       C    200
3       A    120
4       B    180
5       C    220

**7. Clean Data**

In [55]:
df = df.drop_duplicates()
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())
print(df)

  Product  Sales
0       A    100
1       B    150
2       C    200
3       A    120
4       B    180
5       C    220

**8. Sort Data**

In [56]:
print(df.sort_values(by='Sales', ascending=False))

  Product  Sales
5       C    220
2       C    200
4       B    180
1       B    150
3       A    120
0       A    100